version: 2
jobs:
  build:
    docker:
      - image: node:12.13.1-buster-slim
    working_directory: /var/opt/app
    steps:
      - checkout
      - run:
          name: git
          command: |
            apt-get update
            apt-get install -y git
      - restore_cache:
          name: Restoring cache - node_modules
          keys:
            - node_modules-{{ arch }}-node12.13.1-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install packages
          command: yarn install
      - save_cache:
          name: Saving cache - node_modules
          key: node_modules-{{ arch }}-node12.13.1-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: spec
          command: yarn run spec
